il_schedule:
    resource: "@ILScheduleBundle/Resources/config/routing.yml"
    prefix:   /schedule

app:
    resource: '@AppBundle/Controller/'
    type: annotation

login_check:
    path: /login_check

logout:
    path: /logout
