api_controllers:
    resource: ../../src/Controller/Api/
    type: annotation
    prefix: /api
    options:
        expose: true

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
